/*
Script Name:     missing-indexes-report.sql
Purpose:         Reports missing index recommendations from SQL Server DMVs,
                 ordered by an estimated impact score. Includes equality columns,
                 inequality columns, included columns, and an estimated improvement
                 measure.
SQL Server Version: 2005 and later
Required Permissions: VIEW SERVER STATE
Safety Level:    Read-only
How to Use:      Review the output and identify indexes with high impact scores
                 that align with known slow queries. Do not add indexes
                 automatically from this list.
Notes:           *** IMPORTANT ***
                 Missing index suggestions are generated by the query optimizer
                 as it processes queries. They are hints, not instructions.
                 Before creating any index from this list:
                   1. Verify the query the index would help is actually important.
                   2. Check if an existing index covers the same columns.
                   3. Consider the write overhead on INSERT/UPDATE/DELETE.
                   4. Consider consolidating multiple similar suggestions.
                   5. Test the index in a non-production environment first.
                 The impact score formula (seeks * avg_total_user_cost *
                 avg_user_impact) is a rough estimate, not a precise measure.
                 These stats reset when SQL Server restarts.
Author:          Abolfazl Rastgar
*/

SET NOCOUNT ON;

SELECT
    DB_NAME(mid.database_id)                                       AS database_name,
    OBJECT_NAME(mid.object_id, mid.database_id)                   AS table_name,
    mid.equality_columns,
    mid.inequality_columns,
    mid.included_columns,
    migs.unique_compiles,
    migs.user_seeks,
    migs.user_scans,
    migs.avg_total_user_cost,
    migs.avg_user_impact,
    -- Rough impact estimate: seeks weighted by cost and potential improvement
    CAST(
        migs.user_seeks * migs.avg_total_user_cost * (migs.avg_user_impact / 100.0)
    AS DECIMAL(18,2))                                             AS impact_score,
    -- Example CREATE INDEX statement (review and rename before using)
    'CREATE INDEX [IX_' + OBJECT_NAME(mid.object_id, mid.database_id)
        + '_MISSING_' + CAST(mid.index_handle AS VARCHAR(10)) + '] ON '
        + QUOTENAME(DB_NAME(mid.database_id)) + '.'
        + QUOTENAME(OBJECT_SCHEMA_NAME(mid.object_id, mid.database_id)) + '.'
        + QUOTENAME(OBJECT_NAME(mid.object_id, mid.database_id))
        + ' (' + ISNULL(mid.equality_columns, '')
        + CASE
            WHEN mid.inequality_columns IS NOT NULL AND mid.equality_columns IS NOT NULL
                THEN ', ' + mid.inequality_columns
            WHEN mid.inequality_columns IS NOT NULL
                THEN mid.inequality_columns
            ELSE ''
          END + ')'
        + CASE
            WHEN mid.included_columns IS NOT NULL
                THEN ' INCLUDE (' + mid.included_columns + ')'
            ELSE ''
          END
        + ';'                                                      AS suggested_create_index
FROM sys.dm_db_missing_index_details AS mid
INNER JOIN sys.dm_db_missing_index_groups AS mig
    ON mid.index_handle = mig.index_handle
INNER JOIN sys.dm_db_missing_index_group_stats AS migs
    ON mig.index_group_handle = migs.group_handle
ORDER BY
    impact_score DESC;
